apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-demo
  namespace: flux-system
spec:
  interval: 1m
  path: "./apps/podinfo"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
